apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validate.infra-webhooks.svc
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtekNDQW9PZ0F3SUJBZ0lVR1pWa2Y3aUpEUTN3VGp0MHFYZ2t2azBVMWg0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1hURUxNQWtHQTFVRUJoTUNWVk14RlRBVEJnTlZCQWNNREVSbFptRjFiSFFnUTJsMGVURWNNQm9HQTFVRQpDZ3dUUkdWbVlYVnNkQ0JEYjIxd1lXNTVJRXgwWkRFWk1CY0dBMVVFQXd3UWQyVmlhRzl2YXkxMFpYTjBMbk4yCll6QWVGdzB5TVRFeU1UVXlNRE00TkRoYUZ3MHlNakF4TVRReU1ETTRORGhhTUYweEN6QUpCZ05WQkFZVEFsVlQKTVJVd0V3WURWUVFIREF4RVpXWmhkV3gwSUVOcGRIa3hIREFhQmdOVkJBb01FMFJsWm1GMWJIUWdRMjl0Y0dGdQplU0JNZEdReEdUQVhCZ05WQkFNTUVIZGxZbWh2YjJzdGRHVnpkQzV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFETWRyUzgyaDFGdzlkYUJQVFZLbU1qc2Z0amQvRjVZeUpjYTdYRUtRK20KRXdBOXVOV2Job1pFc05Fc0hYQU1GbVFVTlY0T0t1ZjlzVEY0UFp1eHlNWFBxRXU1WWlSWEVyUk10T052czNGSwpRakIzZkg3WlZ4dllwOTcrQjJCZ3h2dTZkeVByUDg5NTdzWXpFdHB1aThVUVE4OVhhOGR3TUNUMzlPcEhuaEJlCnlTVmNvdmM5NVBnNUZpSUZqUDRpUkV6aHk2TlNtdWdmcDZsajMwMUh1M3J6dlhaV0xsWVk3TlBsSEFXYWM1UjgKT0pTRXBpbTJ6Q25LUDgwZXlRNmtyQWN1bWZJQkR3OVdhekhUT0VKeXdMTVFoU2lOQWEzWnIxYXBESkkzR2hDLwp5T1FoQll1ZE5hc2RJSzZYWmU3bjhxcnp6KzN4RDZiVzRSQmtjQ0hQb3RoRkFnTUJBQUdqVXpCUk1CMEdBMVVkCkRnUVdCQlFma3pmUDhXbjhBS1F3SmZ6M1B6aUhGbjdQaHpBZkJnTlZIU01FR0RBV2dCUWZremZQOFduOEFLUXcKSmZ6M1B6aUhGbjdQaHpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDRApTcTBVTGxaWHRXUFl1YVBLbk9SQkRLZFdBMXEwRExmeUdLWFVrNjZHL0xzYUgrTnRFUExaUC96K3lTbmhYNFBVClJkaHExZXpTemlUTS9qZmhWc3lSVEFlRlIxUTZFYTZBdVRyQUYzclpuL3R5Z2hmcXYrM1d6U2ZtQ2tyelliTmoKUXF2OHZ6dlVmUWVacVpwSHFOTDFubzliQ0Vib0tIMVBFbUxmdnlodG5ldzg0STJUalJveXRZT2dpM0NuZk1HZAo0WEUrNW4wSG45T2VCUnd6bktYOEdrYWR5K05YbVRGZ2JXOFFzdmxVMXNweFQ4NHh1QlM5ckNOR3AzWkY2aFdXCmhUNmFVMmxwS09YeW9RQlNYYXVhbGxoRldnVG40MVF1OTZkR1RwN1FHeTJLckZVVlNxbElIaDF0OVF0VHBYOUkKVlhETlU1MFBiMm1BYWRhNGNSd0EKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: validate
      namespace: infra-webhooks
      path: /validate/
      port: 8443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validate.infra-webhooks.svc
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - DELETE
    resources:
    - projects
    - namespaces
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
